spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: user-service
#              uri: http://localhost:8001
#              predicates:
#                - Path=/api/user/**
#            - id: profile-service
#              uri: http://localhost:8002
#              predicates:
#                - Path=/api/profile/**

server:
  port: 8080
jwt:
  secret: U2FmZVJpZGVTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24yMDI2U3ByaW5nQm9vdA==
  expiration: 86400000