spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/profile_db
    username: mohsin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # options: validate, update, create, create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8002