spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: mohsin
    password: secret
  jpa:
    hibernate:
      ddl-auto: create   # options: validate, update, create, create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mughallmohsin938@gmail.com
    password: urplbyykuhehsjsw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8001