spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: mohsin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update   # options: validate, update, create, create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8001
keycloak:
  server-url: http://localhost:9000
  realm: safe_ride
  client-id: ride_sharing_client
  client-secret: QOzyyNcgHPv9VCcQh7NWKfKk9Qgy7WME